### ISSUE TITLE
Speed Limiter Specs wrong

### ISSUE THREAD

**Issue by TheralSadurns** [evkx/evkx.github.io#18]
A lot of cars (such as NIO and Tesla cars) wrongly list a "Speed Limiter" as standard equipment, which is factually wrong. Tesla may have a speed limit mode, that allows you to set a global max speed. A speed limiter, however is a completely different function and dynamic in nature and can be changed on the fly akin to ACC. 

Speed Limiter should be changed to NO, not available for all Tesla and NIO vehicles

**Comment by TheTechArch** [comment]
@TheralSadurns, thanks for taking the time to provide feedback. I have been thinking about this feature because it is original, based on the speed limiter function Audi has, where you can set it to a value, and with regular driving, you will not pass that limit. But it is confusing since many think it is about the "Follow speed limit" in ACC that most cars have support for. 

I am leaning just toward removing the spec feature anyway since it is mostly irrelevant for most cars and, as you say confusing since brands can mention speed limiter related to

**Comment by TheTechArch** [comment]
I have now removed this spec for all models. Thanks for the feedback helping to improve the site.
